SymEdit\Bundle\UserBundle\Model\User:
    properties:
        profile:
            - Valid: ~
    constraints:
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email

SymEdit\Bundle\UserBundle\Model\Profile:
    properties:
        firstName:
            - NotBlank: ~

SymEdit\Bundle\UserBundle\Model\AdminProfile:
    properties:
        image:
            - Valid: ~
