SymEdit\Bundle\UserBundle\Model\AdminProfile:
    type: mappedSuperclass
    table: admin_profile
    fields:
        social:
            type: json_array
            nullable: true
        summary:
            type: text
            nullable: true
        biography:
            type: text
            nullable: true
        display:
            type: boolean
        slug:
            type: text
            gedmo:
                slug:
                    separator: "-"
                    fields:
                        - firstName
                        - lastName
    manyToOne:
        image:
            targetEntity: SymEdit\Bundle\MediaBundle\Model\ImageInterface
            cascade:
                - persist
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
